package: remove problematic 'src' dir
'src' dir was causing:
AssertionError: Egg-link […] does not match installed location when symlinks added to venv path

When running:
python3 -m pip install -e .[dev]

Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>